FROM ubuntu

MAINTAINER Gajo Petrovic, gajop01@gmail.com

RUN echo 'http_proxy=http://proxy.uns.ac.rs:8080' >> /etc/environment
RUN echo 'deb http://archive.ubuntu.com/ubuntu precise main universe' > /etc/apt/sources.list
RUN http_proxy=http://proxy.uns.ac.rs:8080 apt-get update -y -q
RUN http_proxy=http://proxy.uns.ac.rs:8080 apt-get install -y -q python-pip
RUN http_proxy=http://proxy.uns.ac.rs:8080 apt-get install -y -q octave

ADD invoker.py invoker.py
ADD runner.m runner.m
